spring.application.name=Proyecto1
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

management.endpoints.web.exposure.exclude=health,info

spring.security.user.name=ivan
sprin.security.user.password=12345

info.app.name=Mi aplicacion
info.app.description=Es una aplicacion con el objetivo de aprender Spring Boot
info.app.version=1.0.0
